### ISSUE TITLE
Improve documentation for getting access token the official way

### ISSUE THREAD

**Issue by C0rn3j** [arpanghosh8453/fitbit-web-ui-app#2]
Hi, I am trying to get this working but the sparse information for the official way section made me struggle a lot.

> Visit [this page](https://dev.fitbit.com/build/reference/web-api/developer-guide/getting-started/) and follow tutorial to create your own application

Inform user that a read-only API key will suffice, as I do not see a reason for this page to need write.

If it needs write, include rationale.

Redirect URI seems to need some endpoint, so probably tell user to do EXAMPLE.COM/test or simialr.

![image](https://github.com/arpanghosh8453/fitbit-web-ui-app/assets/1641362/0c4694f9-be88-41e1-9c36-af6f93dc7863)

> Open [this page](https://dev.fitbit.com/build/reference/web-api/troubleshooting-guide/oauth2-tutorial/?clientEncodedId=23R3K5&redirectUri=https://localhost:8000/&applicationType=PERSONAL) and continue the process

I presume Server type is necessary here(not Client), so fill that in.

Replace Client ID and Client Secret with those of your own application.

Click the two generate buttons in Step 1.

Here's where I hit a big snag, the URL in step 2 did not seem to contain my registered callback URL.

![image](https://github.com/arpanghosh8453/fitbit-web-ui-app/assets/1641362/4eb8ed65-9584-4b6b-82d2-4daf63f4f827)

![image](https://github.com/arpanghosh8453/fitbit-web-ui-app/assets/1641362/0384a702-0196-4712-9f50-da5679605185)

I manually removed the redirect_uri parameter from the URL and that worked. What would be the correct approach here?

>After you authorize your own application, you will get a ACCESS TOKEN and REFRESH TOKEN after following the whole process

> REMEMBER : Each API key has an hourly call limit and expires forever after 8 hours. One key will not work forever. If you use the same key in quick succession, you may hit the hourly rate limit.

Couldn't you also accept the refresh token and generate a new access token as needed?

**Comment by arpanghosh8453** [comment]
The redirect URL should be something like https://localhost:8000/ where you can redirect so you can copy everything from the redirected url bar which contains the auth code. A read only API works fine. It can be server type or client type ( that won't matter )

I deliberately avoided the refresh token option because you generate this chart once every few months and I am not hosting a persistent server. I am not storing any data from the user so I am not taking in any refresh token for persistent access.

**Comment by C0rn3j** [comment]
> The redirect URL should be something like https://localhost:8000/ where you can redirect so you can copy everything from the redirected url bar which contains the auth code.

This did not work for me, as per the error screenshot, could you show how you have your app setup in case it's some oddity?

> I deliberately avoided the refresh token option because you generate this chart once every few months and I am not hosting a persistent server.

This however means that it's up to the user re-generating the token outside of the application, instead of just providing the same refresh token, I believe it'd be possible to use the refresh token on the client side so the user doesn't have to keep going through the annoying setup process repeatedly (or get a new token on the CLI if they're so inclined).

For example I would like to save the refresh token in my password manager and just copy paste it when necessary to use in this app.

**Comment by arpanghosh8453** [comment]
if you use https://localhost:8000/ it will indeed show the page cannot be reached once you click allow, but you just need to copy the whole url bar and paste it in the given text box and it will filter the tokens out. 

The refresh token changes every time you request an access token with it. You do not need to redo the whole app creation process. You can send a curl request with your refresh token ( as shown on the oauth tutorial page ), get a new access and refresh token pair, save the refresh token for next time, and use the new access token. It's better for security if the client handles the access token so the access is not persistent for my server.
