### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by C0rn3j** [arpanghosh8453/fitbit-web-ui-app#4]
Since you're keeping the code available, I presume you'd either want a restrictive open source license to get back any changes from people using the project, in which case AGPLv3 would suit this project.

Or if you want anyone to be able to do any modifications and keep them to themselves, something like the permissible MIT/BSD/... would be a better choice.

**Comment by arpanghosh8453** [comment]
Thank you for mentioning this. I have added a BSD 3-clause license to this project.
