### ISSUE TITLE
Make it obvious when there was an error and do not lock out the buttons

### ISSUE THREAD

**Issue by C0rn3j** [arpanghosh8453/fitbit-web-ui-app#5]
At the moment if the server fails to grab the data, loading animation disappears and it seems to the user as if nothing happened.

The date picker and submit buttons are also locked up when this happens and a site reload is needed to attempt anything else.

![image](https://github.com/arpanghosh8453/fitbit-web-ui-app/assets/1641362/185f2b77-3c4e-4ce0-8138-3d7935c1eaf5)

**Comment by arpanghosh8453** [comment]
I locked the buttons to avoid user clicking it multiple times while the API calls are in progress. And it's just one time visualization so one your hit start, there is no need for that button to be active. If you need to re-use it, you need to reload. 

And if the server fails, it's probably a 5xx error from the Fitbit server which means you just need to retry later. If the Auth token is invalid, it will display that in a message.

**Comment by C0rn3j** [comment]
> I locked the buttons to avoid user clicking it multiple times while the API calls are in progress.

That makes sense.

> And if the server fails, it's probably a 5xx error from the Fitbit server which means you just need to retry later. 

This error is however not caught, which was the point of the issue.

A "We got a XXX error from Fitbit, try again later" would sort it.

Also unlocking the buttons after an error instead of a success would make sense to me, as the user would definitely want to retry and have a valid reason for it in that case.
