### ISSUE TITLE
SpO2 description does not mention it is sleep SpO2

### ISSUE THREAD

**Issue by C0rn3j** [arpanghosh8453/fitbit-web-ui-app#6]
Currently it makes it look like it is regular daily SpO2, but it is actually nightly.

The graph also has a fully capitalized `SPO2` instead of `SpO2`, which seems like a typo.

Fitbit description of the feature: 

![image](https://github.com/arpanghosh8453/fitbit-web-ui-app/assets/1641362/b492b410-18e2-46c2-bf09-373c433f442b)

**Comment by arpanghosh8453** [comment]
Fitbit collects SpO2 data only at night, so the recorded data is always nightly SpO2. 

And yes, that is a typo. Thank you for pointing that out.
